-- CreateTable
CREATE TABLE "FireDetection" (
    "id" TEXT NOT NULL,
    "timestamp" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "label" TEXT NOT NULL,
    "confidence" DOUBLE PRECISION NOT NULL,
    "bboxX1" DOUBLE PRECISION NOT NULL,
    "bboxY1" DOUBLE PRECISION NOT NULL,
    "bboxX2" DOUBLE PRECISION NOT NULL,
    "bboxY2" DOUBLE PRECISION NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'ACTIVE',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "FireDetection_pkey" PRIMARY KEY ("id")
);
